name: New Post Webhook

on:
  push:
    branches:
      - "coal"
    paths:
      - "posts/**/post.mdx"

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/coal'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Find New post.mdx Files
        id: check_new_files
        run: |
          git fetch origin main
          NEW_POST=$(git diff --name-only --diff-filter=A HEAD~1 HEAD | grep -o 'posts/[^/]*/post\.mdx' | sed 's|posts/\(.*\)/post\.mdx|\1|')
          if [ -n "$NEW_POST" ]; then
            echo "NEW_POST=$NEW_POST" >> $GITHUB_ENV
            echo "new post: $NEW_POST"
          else
            echo "no new posts"
          fi

      - name: Set up Node.js
        if: env.NEW_POST != ''
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        
      - name: Install Dependencies
        if: env.NEW_POST != ''
        run: npm install
        
#      - name: Wait 5 minutes
#        if: env.NEW_POST != ''
#        run: sleep 300
        
      - name: Run Script
        if: env.NEW_POST != ''
        run: npx tsx scripts/new-post-webhook.ts ${{ env.NEW_POST }}
